### ISSUE TITLE
Weapon Miss Cooldowns

### ISSUE THREAD

**Issue by AWalkableScrub** [ThrawnGames22/Lichs_Lair_Game#13]
Doesnt have to be done by VSlice but i think itd be a really nice QOL change if we made it so that missed weapon attacks get a 3 second cooldown instead of making you wait the full duration. I think make it 3 seconds so players cant fire off multiple attacks before an attack lands and it also makes it so that missing is still punished somewhat.

**Comment by ThrawnGames22** [comment]
At this point it would be complicated but I could consider it for S2

**Comment by ThrawnGames22** [comment]
But i am changing the cooldowns for melee weapons to longer tommorow
