### ISSUE TITLE
Unity Back up for test build

### ISSUE THREAD

**Issue by Chetaung23** [ThrawnGames22/Lichs_Lair_Game#17]
I worked on adding in some props for level 2 and am done. I can't push it for some reason so I have made a Back up save for now. Until it's safe to be pushed again, it will remain an issue.

**Comment by ThrawnGames22** [comment]
Im going to resolve that as soon as possible

**Comment by ThrawnGames22** [comment]
New Repo https://github.com/ThrawnGames22/Lichs-Lair-Recovery
