### ISSUE TITLE
Issues from the first testing results

### ISSUE THREAD

**Issue by Chetaung23** [ThrawnGames22/Lichs_Lair_Game#2]
**Not yet fixed** - Jump dash only works with movement key – Dash gain height – 

**Not yet fixed** - Jump dash – need to work horizontally 
	- should also work while standing

**Comment by Chetaung23** [comment]
Few of these are now fixed and removed from the list. It is then moved to a closed issue section for issues regarding first testing result that got fixed.

**Comment by ThrawnGames22** [comment]
Issues Resolved
