### ISSUE TITLE
Getting level sizes correct

### ISSUE THREAD

**Issue by Chetaung23** [ThrawnGames22/Lichs_Lair_Game#30]
still fiddling with the level sizes and not fully finalise on them yet. As we as, importing few into the maya scene for the PGF.

**Comment by Chetaung23** [comment]
currently, levels are sized to 80x80x80

Not too sure about the amount of levels we are importing for the PGF but aiming for at least 5 at this moment.

**Comment by ThrawnGames22** [comment]
sizes are correct

**Comment by ThrawnGames22** [comment]
All rooms are resized appropriately
