### ISSUE TITLE
Test no.2

### ISSUE THREAD

**Issue by Chetaung23** [ThrawnGames22/Lichs_Lair_Game#4]
**_Good –_** 
Camera is looking great but maybe a bit more up so it’s a bit more top down

**_Maybe touch on_**  

**Fixed** - Health above enemy – show health for enemy

**Not yet Fixed** - Maybe can dash while mobiled – or can stay as dash only when moving 

**Fixed** - Can jump faster? – less mass? If cant its ok – its goin good.

**Null** - Combat a bit confusing – so left is spell and right is spell too – melee slash is x or e. In my opinion maybe left click for melee and right click for only spells – that way mouse is not useless when mana is depleted for spells.

**Not Yet Fixed** - Able to damage enemy with spells – interaction
-Dark slash works – 
-Fireball – not yet

**Not yet fixed** - Null - Attack melee faster – faster animation maybe – cannot land hits easily without getting damaged 

**Fixed** - Icon show only the skills being in use instead of showing all 4 on the screen. – only if you have time (not super important)

**Fixed** - Player health and mana next to icons if possible for UI

 **Fixed** - Key bind for inventory – letter or key as ‘I’

**Fixed** - Clicking other parts of the screen triggers spells or combat – maybe a way to not trigger the combat controls when clicking other inputs so it doesn’t confuse the player or them using up the mana pool for unreasonable reason when clicking other stuff.

**Comment by ThrawnGames22** [comment]
Health above enemy is a work in progress
