### ISSUE TITLE
Test 3

### ISSUE THREAD

**Issue by Chetaung23** [ThrawnGames22/Lichs_Lair_Game#6]
**Need touch on or fix**

Jump dash levitates the player up – needs fixing on to not do that but instead dash horizontally. 

Melee attack faster or respond more to each click, maybe. The melee attack is delayed atm. – but because melee is strong, this feature can be ignored.

Foe getting knock back when interacted by melee attack. This feature can be ignored if it comes to the point of taking too much time to implement.

Camera keeps jittering - clipping

**Comment by ThrawnGames22** [comment]
Jump dash is still a persistant issue but planning to resolve it tomorrow
