### ISSUE TITLE
Dash Launches player when they jump

### ISSUE THREAD

**Issue by AWalkableScrub** [ThrawnGames22/Lichs_Lair_Game#9]
If you dash while jumping, it will launch the player in the current vector they are moving in.

**To recreate**: Jump, then dash. particularly noticeable if you stand still and jump directly up.

Dash seems to be based on the direction that the player is moving, change it to the direction that the player **model** is facing.

**Comment by ThrawnGames22** [comment]
Fixing this issue Tommorow
